apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: monitor
spec:
  version: 8.4.3
  nodeSets:
  - name: es-cluster
    count: 2
    config:
      node.store.allow_mmap: false

#refer https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html