apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: monitor
spec:
  version: 8.4.3
  nodeSets:
  - name: es-cluster
    count: 2
    config:
      node.store.allow_mmap: false